//*here is how you need to import the sessionProvider component to be able to protect the front end pages
import { SessionProvider } from '@/components/AuthProvider';

import Nav from '@/components/Nav';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
      {/* First you create the tag and then you import it */}
			<SessionProvider>
				<body className={inter.className}>
					<Nav />
					{children}
				</body>
			</SessionProvider>
		</html>
	);
}
